name: release-build

on:
  push:
    # tags:
      # - v*.*.*
    branches:
      - v1 

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [windows-latest, macos-latest, ubuntu-latest]
        # os: [windows-latest, macos-latest]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: build windows app
        run: |
          yarn
          yarn release
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.VUE3_ELECTRON }}
      - name: upload file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: dist_electron
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist_electron/*.exe
            dist_electron/*.dmg
            dist_electron/*.AppImage
            dist_electron/latest-linux.yml
            dist_electron/latest-mac.yml
            dist_electron/latest.yml
        env:
          GITHUB_TOKEN: ${{ secrets.VUE3_ELECTRON }}